### ISSUE TITLE
Invalid - pygobject==3.26.1

### ISSUE THREAD

**Issue by ak0der1** [smkhassan/InstaBotFarmvile#1]
While installing all requirements, I found this error.

"Could not find a version that satisfies the requirement pygobject==3.26.1 (from -r requirements.txt (line 25)) (from versions: 3.27.0, 3.27.1, 3.27.2, 3.27.3, 3.27.4, 3.27.5, 3.28.0, 3.28.1, 3.28.2, 3.28.3, 3.29.1.dev0, 3.29.2.dev0, 3.29.3.dev0, 3.30.0, 3.30.1, 3.30.2, 3.30.3, 3.30.4, 3.31.1.dev0, 3.31.2.dev0, 3.31.3.dev0, 3.31.4.dev0, 3.32.0, 3.32.1)
No matching distribution found for pygobject==3.26.1 (from -r requirements.txt (line 25))"

I tried to install from
https://pypi.org/project/PyGObject/

Still didn't work

I am using Mac with Python 3.7

**Comment by smkhassan** [comment]
sudo apt-get -y install python3
sudo apt-get -y install python-pip
sudo pip innstall selenium
sudo pip install instabot


Try this.

**Comment by 123THU** [comment]
no use....

**Comment by 123THU** [comment]
btw useless.....

**Comment by 123THU** [comment]
btw useless.... try this: [pygobject 3.26.1-1 source package in Ubuntu
](https://launchpad.net/ubuntu/+source/pygobject/3.26.1-1)
